server.port=8081
spring.application.name=gameplay-service

# Eureka - disable nếu chưa dựng Eureka Server
eureka.client.enabled=false

# Disable JDBC and JPA auto-configurations since we only use Redis
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Avoid standard redis om repos conflicting
spring.data.redis.repositories.enabled=false

# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9094

spring.kafka.consumer.group-id=gameplay-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

# sử dụng ErrorHandlingDeserializer
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# ? JSON config
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.werewolf.gameplay.model.events.RoomStartedEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.listener.ack-mode=MANUAL_IMMEDIATE

# producer OK r?i
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
